version: '3.8'

services:  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tyfor
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tyfor"]
      interval: 10s
      timeout: 5s
      retries: 5
  # TYFOR Application (Development)
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=
      - JWT_SECRET_KEY=dev_jwt_secret_key_change_in_production
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SECRET_KEY=dev_secret_key_change_in_production
      - PYTHONPATH=/app/backend
    ports:
      - "5056:5056"
      - "3000:3000"  # React dev server
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
      - ./data:/app/data
      - /app/backend/__pycache__  # Exclude pycache
      - /app/frontend/node_modules  # Exclude node_modules
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
