version: '3.8'

services:  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: tyfor
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tyfor"]
      interval: 10s
      timeout: 5s
      retries: 5
  # TYFOR Application
  app:
    build: .
    environment:
      - DATABASE_URL=
      - JWT_SECRET_KEY=
      - FLASK_ENV=production
      - SECRET_KEY=
      - PYTHONPATH=/app/backend
    ports:
      - "5056:5056"
    volumes:
      - ./backend/uploads:/app/backend/uploads
      - ./backend/static/graphs:/app/backend/static/graphs
      - ./data:/app/data
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
